### ISSUE TITLE
Potential Misconfiguration

### ISSUE THREAD

**Issue by santolucito** [laukstein/ajax-seo#28]
We are a group of researchers from Yale University building a tool to finding bugs in configurations files. To evaluate the effectiveness of our tool, we randomly selected 1000 open source configuration files to verify and are requesting feedback on our error report. Your file https://raw.githubusercontent.com/laukstein/ajax-seo/4df050097c8b1b01b49e0b559b6b77b8d34ab5fe/~config/my.cnf was among those files. When we ran our tool your file, it reported the following potential errors.

[INTEGER RELATION ERROR: Expected slow-query-log[mysqld] <= max-allowed-packet[mysqld] 
 Found values: ["max-allowed-packet[mysqld]=1m","slow-query-log[mysqld]=1","slow-query-log[mysqld]=1"]
 In the training set we saw: ">=" 0 times, "<=" 32 times, "==" 0 times

INTEGER RELATION ERROR: Expected query-cache-type[mysqld] <= max-allowed-packet[mysqld] 
 Found values: ["max-allowed-packet[mysqld]=1m","query-cache-type[mysqld]=1"]
 In the training set we saw: ">=" 0 times, "<=" 55 times, "==" 1 times

FINE GRAINED ERROR: Expected max-connections[mysqld] * read-buffer-size[mysqld] >= myisam-sort-buffer-size[mysqld] 
 Found values: ["max-connections[mysqld]=38","read-buffer-size[mysqld]=1m","myisam-sort-buffer-size[mysqld]=64m"]
 In the training set we saw: ">=" 73 times, "<=" 3 times, "==" 0 times
]

The training set referenced in the report is taken from the industrial configuration files at https://github.com/tianyin/configuration_datasets. Note that even if your system is currently working, these bug may manifest itself only under large traffic loads or different system environments. 

If you feel the any of above errors may indeed cause problems either on your system, or a different system, please comment on this issue report in the space below. This will help use to improve our tool. If you do not believe this is a potential bug, please feel free to close this issue. If possible we would appreciate your feedback before July 27.

If you would like find out more about how we detected these bug, you can find the open source tool at https://github.com/santolucito/ConfigV. For a quick overview of this tool, you can watch this video at https://youtu.be/plliEh-5MpM. If you have further questions, or would like to get involved with this project, feel free to reach out over email at mark.santolucito@yale.edu.

Thank you for your time!

**Comment by laukstein** [comment]
Hi, @santolucito!
[ajax-seo@my.cnf](https://github.com/laukstein/ajax-seo/blob/master/~config/my.cnf) is based on default [mariadb@my-large.cnf](https://github.com/atcurtis/mariadb/blob/master/support-files/my-large.cnf.sh) + optimized for low RAM servers. I haven't noticed issues width recent my.cnf in real world cases.
Did you tried to test MariaDB default configurations? It seems to me your testing tool has bugs. Notice also that [ajax-seo@~config](https://github.com/laukstein/ajax-seo/tree/master/~config) includes only partial configurations (not full php.ini, etc.).

Please provide more details and your recommendation, otherwise this issue is irrelevant.
